server:
  port: 8010
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-consumer-movie

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

#<clientName>.ribbon. 如下属性
#NFLoadBalancerClassName: should implement ILoadBalancer
#NFLoadBalancerRuleClassName: should implement IRule
#NFLoadBalancerPingClassName: should implement IPing
#NIWSServerListClassName: should implement ServerList
#NIWSServerListFilterClassName: should implement ServerListFilter

microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#默认情况下Ribbon是懒加载的——首次请求Ribbon相关类才会初始化，这会导致首次请求过慢的问题，
#你可以配置饥饿加载，让Ribbon在应用启动时就初始化。
ribbon:
  eager-load:
    clients: microservice-provider-user